### ISSUE TITLE
[graphql] Fix writing to closed channel

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/zindexer#10]
When grapghqlClient reset its connection, program tries to write to a closed channel.

BT:

```
2021-07-09T13:33:28.203Z        DEBUG   [ModuleId-Dummy] Publishing: %!s(int=1139)
panic: send on closed channel
goroutine 37 [running]:
github.com/Zondax/zindexer/connections.GraphqlSubscriptionClient.Start.func1()
        /go/pkg/mod/github.com/!zondax/zindexer@v0.0.3-0.20210607221602-a6b4d6bd58f9/connections/graphql.go:78 +0x36
github.com/hasura/go-graphql-client.(*SubscriptionClient).Run(0xc0002d6180, 0xc3f240, 0xc0001a6500)
        /go/pkg/mod/github.com/hasura/go-graphql-client@v0.2.0/subscription.go:446 +0xadc
github.com/hasura/go-graphql-client.(*SubscriptionClient).Reset(0xc0002d6180, 0x53, 0xb6e739)
        /go/pkg/mod/github.com/hasura/go-graphql-client@v0.2.0/subscription.go:528 +0x10f
github.com/hasura/go-graphql-client.(*SubscriptionClient).Run(0xc0002d6180, 0x0, 0x0)
        /go/pkg/mod/github.com/hasura/go-graphql-client@v0.2.0/subscription.go:385 +0xda5
github.com/Zondax/zindexer/connections.GraphqlSubscriptionClient.Start.func2(0xc0002d6180, 0x0, 0x0, 0xc000292360)
        /go/pkg/mod/github.com/!zondax/zindexer@v0.0.3-0.20210607221602-a6b4d6bd58f9/connections/graphql.go:82 +0x2b
created by github.com/Zondax/zindexer/connections.GraphqlSubscriptionClient.Start
        /go/pkg/mod/github.com/!zondax/zindexer@v0.0.3-0.20210607221602-a6b4d6bd58f9/connections/graphql.go:81 +0x10e
```

**Comment by raynaudoe** [comment]
Fixed on release `v0.2.0`
